version: 2.1
jobs:
    test:
        docker:
            - image: circleci/node:latest 
        steps:
            - checkout
            - run:
                name: Versions
                command: |
                    node --version
                    npm --version
            - run:
                name: Dependencies
                command: npm install
            - run:
                name: Tests
                command: npm test
            - persist_to_workspace:
                root: .
    build:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run:
                name: Build
                command: npm run build
            - persist_to_workspace:
                root: .
                paths:
                    - ./build
    publish:
        docker:
            - image: circleci/python:latest-node
        steps:
            - run:
                name: Publish
                command: |
                    curl -O https://bootstrap.pypa.io/get-pip.py
                    python3 get-pip.py --user
                    pip3 install awscli --upgrade --user
                    export PATH=/home/circleci/.local/bin:$PATH
workflows:
    version: 2
    workflow:
        jobs:
        - test
        - build:
            requires:
              - test
        - publish:
            context: AWS Deploy
            requires:
              - build